### PR TITLE
Refactor role to take a more complex variable as input.

### PR DESCRIPTION
**Pull request by bensallen**
Refactor role to take a more complex variable as input. Allowing for numerous hosts to be added. Rename other variables to be more unique to role. Also fix library to only replace/remove a key that matches the same encryption type, allowing for entry of the same host with different encryption types.

### CODE REVIEW

**Comment by bfmartin** [comment]
Nice patches. Thank you.

**Comment by bfmartin** [comment]
@bensallen, have you compared this role to the new built-in module in Ansible 1.9?

**Comment by bensallen** [comment]
Assume you mean https://github.com/ansible/ansible-modules-extras/blob/devel/system/known_hosts.py? This role has the nice benefit of being able to scan for the keys. The new built-in requires you to specify the pub key in some way.

**Comment by bfmartin** [comment]
Let's hope that's improved in the future. Thanks once again.

**Pull request merged**
